/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Control.ControladorTablero;
import Modelo.Tripleta;
import java.util.List;
import java.util.function.Consumer;
/**
 *
 * @author Sofito-Chan
 */
public class TableroJuego extends javax.swing.JFrame {

    int filas=8;
    int cols=8;
    int minas=5;
    JButton[][] botonesTablero;
    ControladorTablero tableroBuscaminas = new ControladorTablero();;
    /**
     * Creates new form Controles
     */
    public TableroJuego() {
        initComponents();
        cargarControles(filas, cols);
        crearTablero();
    }

    public void crearTablero(){
        tableroBuscaminas.crear(filas, cols, minas);
        tableroBuscaminas.setEventoPartidaPerdida(new Consumer<List<Tripleta>>() {
            @Override
            public void accept(List<Tripleta> t) {
                for(Tripleta casilla: t){
                    botonesTablero[casilla.retornaFila()-1][casilla.retornaColumna()-1].setText("*");
                }
            }
        });
        tableroBuscaminas.setEventoPartidaGanada(new Consumer<List<Tripleta>>() {
            @Override
            public void accept(List<Tripleta> t) {
                for(Tripleta casilla: t){
                    botonesTablero[casilla.retornaFila()-1][casilla.retornaColumna()-1].setText("Ü");
                }
            }
        });
        tableroBuscaminas.setCasillaAbierta(new Consumer<List<Tripleta>>() {
            @Override
            public void accept(List<Tripleta> ti) {
                for(Tripleta t: ti){
                    if(t.retornaFila()==0 || t.retornaColumna() == 0){
                        JOptionPane.showMessageDialog(rootPane, "Algo anda mal...");
                        break;
                    }
                    if(botonesTablero[t.retornaFila()-1][t.retornaColumna()-1].isEnabled()){
                        botonesTablero[t.retornaFila()-1][t.retornaColumna()-1].setEnabled(false);
                    }   
                    int valor = (int)t.retornaValor();
                    if(0 != (int)t.retornaValor()){
                        botonesTablero[t.retornaFila()-1][t.retornaColumna()-1].setText(t.retornaValor()+"");                       
                    }
                    else{
                        botonesTablero[t.retornaFila()-1][t.retornaColumna()-1].setText("");
                    } 
                }
                
                            
            }
        });
        tableroBuscaminas.getTablero().muestraMatriz();
    }
    
    public void cargarControles(int filas, int cols){
        int posXInicial =7;
        int posYInicial = 7;
        botonesTablero = new JButton[filas][cols];
        for (int i = 0; i < botonesTablero.length; i++) {
            for (int j = 0; j < botonesTablero[i].length; j++) {
                botonesTablero[i][j] = new JButton();
                botonesTablero[i][j].setName((i+1) + "," + (j+1));
                botonesTablero[i][j].setBorder(null);
                if(i ==0 && j==0){
                    botonesTablero[i][j].setBounds(posXInicial, posYInicial, 30, 30);
                }
                else if(i==0 && j !=0 ){
                    botonesTablero[i][j].setBounds(
                            botonesTablero[i][j-1].getX()+botonesTablero[i][j-1].getWidth(), posYInicial, 30, 30);
                }
                else{
                    botonesTablero[i][j].setBounds(
                            botonesTablero[i-1][j].getX(),
                            botonesTablero[i-1][j].getY() + botonesTablero[i-1][j].getHeight(), 30, 30);            
                }
                botonesTablero[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        btnClick(e);
                    }
                });
                Minas.add(botonesTablero[i][j]);
            }
        }
    }
    
    private void btnClick(ActionEvent e) {
        JButton btn = (JButton)e.getSource();
        String[]coordenada = btn.getName().split(",");
        int fila = Integer.valueOf(coordenada[0]);
        int col = Integer.valueOf(coordenada[1]);
        JOptionPane.showMessageDialog(rootPane, fila +","+col);
        tableroBuscaminas.seleccionarCasilla(fila, col);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navegacion = new javax.swing.JPanel();
        MenuBoton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NroDeMinasPane = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TiempoPane = new javax.swing.JTextPane();
        Minas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Navegacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Navegacion.setToolTipText("");
        Navegacion.setFocusable(false);
        Navegacion.setName(""); // NOI18N

        MenuBoton.setText("♥");
        MenuBoton.setActionCommand("");
        MenuBoton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuBoton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuBoton.setName("MenuBoton"); // NOI18N
        MenuBoton.setVerifyInputWhenFocusTarget(false);

        NroDeMinasPane.setEditable(false);
        NroDeMinasPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(NroDeMinasPane);

        TiempoPane.setEditable(false);
        TiempoPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(TiempoPane);
        TiempoPane.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout NavegacionLayout = new javax.swing.GroupLayout(Navegacion);
        Navegacion.setLayout(NavegacionLayout);
        NavegacionLayout.setHorizontalGroup(
            NavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavegacionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(MenuBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NavegacionLayout.setVerticalGroup(
            NavegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addComponent(MenuBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        MenuBoton.getAccessibleContext().setAccessibleName("Menu");
        MenuBoton.getAccessibleContext().setAccessibleDescription("");

        Minas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout MinasLayout = new javax.swing.GroupLayout(Minas);
        Minas.setLayout(MinasLayout);
        MinasLayout.setHorizontalGroup(
            MinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MinasLayout.setVerticalGroup(
            MinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navegacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Minas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Minas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Navegacion.getAccessibleContext().setAccessibleName("Navegacion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton MenuBoton;
    private javax.swing.JPanel Minas;
    private javax.swing.JPanel Navegacion;
    private javax.swing.JTextPane NroDeMinasPane;
    private javax.swing.JTextPane TiempoPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
